### ISSUE TITLE
The package doesn't work

### ISSUE THREAD

**Issue by yuewangpanda** [lgnbhl/gotop#1]
Hi,

Thank you for creating this very useful package. However, it doesn't work on my end.  My code is 

```{r, echo=FALSE, results='asis'}
knitr::kable(head(mtcars, 10))
```

```{r, echo=FALSE}
gotop::use_gotop(
  src = "fas fa-chevron-circle-up", 
  color = "tomato", 
  width = 30
  )
```

However, there has no icons in the output html file. 
![Screen Shot 2020-10-22 at 11 56 53 AM](https://user-images.githubusercontent.com/36970568/96898440-b66c5880-145d-11eb-93e8-4c7b10f7e882.png)

Please help me out. Thanks!

**Comment by lgnbhl** [comment]
Hi,

Thank you for your interest in my package.

A reason why the gotop icon didn't appear could be that your HTML file is not long enough.

You can control the amount of pixels the page must be scrolled down before the gotop icon appears by using the `appear` argument. You could try for example:

```
gotop::use_gotop(
  src = "fas fa-chevron-circle-up", 
  color = "tomato", 
  width = 30,
  appear = 0
  )
```

Please let me know if it fixes the issue.

Best,
Félix
